#!/usr/bin/env python3
"""Audit the full Discord voice meeting pipeline.

Run this before testing meetings to catch broken components early.
Checks: meetings dir, code changes, systemd unit (incl. drop-in override),
gateway logs, Z.AI key validity.

Usage:
    python3 scripts/audit-meeting-pipeline.py
"""
import os
import json
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

GATEWAY_LOG = Path.home() / ".hermes" / "logs" / "gateway.log"
MEETINGS_DIR = Path.home() / ".hermes" / "meetings" / "discord"
HERMES_AGENT = Path.home() / ".hermes" / "hermes-agent"
SYSTEMD_UNIT = Path.home() / ".config" / "systemd" / "user" / "hermes-gateway.service"
SYSTEMD_DROPIN = Path.home() / ".config" / "systemd" / "user" / "hermes-gateway.service.d" / "override.conf"
ENV_FILE = Path.home() / ".hermes" / ".env"
WRAPPER_SCRIPT = Path.home() / ".hermes" / "scripts" / "hermes-gateway-with-1password.sh"

CHECKS = []


def ok(msg):
    CHECKS.append(("OK", msg))
    print(f"  \033[32m✓\033[0m {msg}")


def warn(msg):
    CHECKS.append(("WARN", msg))
    print(f"  \033[33m!\033[0m {msg}")


def fail(msg):
    CHECKS.append(("FAIL", msg))
    print(f"  \033[31m✗\033[0m {msg}")


def header(title):
    print(f"\n{'='*60}")
    print(f"  {title}")
    print(f"{'='*60}")


def probe_zai_endpoint(endpoint_url, glm_key, timeout=10):
    """Probe Z.AI without putting the bearer token in process arguments."""
    payload = json.dumps({
        "model": "glm-4.6",
        "messages": [{"role": "user", "content": "ok"}],
        "max_tokens": 5,
    }).encode("utf-8")
    req = urllib.request.Request(
        endpoint_url,
        data=payload,
        headers={
            "Authorization": f"Bearer {glm_key}",
            "Content-Type": "application/json",
        },
        method="POST",
    )
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return resp.read().decode("utf-8", errors="replace")
    except urllib.error.HTTPError as exc:
        return exc.read().decode("utf-8", errors="replace")
    except Exception as exc:
        return json.dumps({"error": str(exc)})


# --- 1. Meetings directory ---
header("1. MEETINGS DIRECTORY")
if MEETINGS_DIR.exists():
    atas = list(MEETINGS_DIR.rglob("*.md"))
    ok(f"{len(atas)} ata(s) found")
    empty_count = 0
    for ata in sorted(atas, reverse=True)[:5]:
        content = ata.read_text()
        lines = [l for l in content.splitlines() if l.strip().startswith("- `")]
        if not lines:
            empty_count += 1
            warn(f"  {ata.name}: 0 transcript entries (possible race condition)")
        else:
            ok(f"  {ata.name}: {len(lines)} entries")
    if empty_count > 0:
        warn(f"  {empty_count}/{min(len(atas),5)} recent atas have 0 entries")
else:
    fail("Meetings directory does not exist")


# --- 2. Code changes ---
header("2. UNCOMMITTED CODE CHANGES")
result = subprocess.run(
    ["git", "diff", "--stat", "HEAD"],
    capture_output=True, text=True, cwd=str(HERMES_AGENT)
)
if result.stdout.strip():
    for line in result.stdout.strip().splitlines():
        parts = line.split()
        if len(parts) >= 2:
            ok(f"Modified: {parts[0]} ({parts[-1]})")
        else:
            ok(f"Modified: {line.strip()}")
    grep_result = subprocess.run(
        ["grep", "-c", "_handle_meeting_command", "gateway/run.py"],
        capture_output=True, text=True, cwd=str(HERMES_AGENT)
    )
    count = int(grep_result.stdout.strip()) if grep_result.stdout.strip().isdigit() else 0
    if count > 0:
        ok(f"_handle_meeting_command present in run.py ({count} references)")
    else:
        fail("Meeting command handler not found in run.py")
else:
    ok("No uncommitted changes")


# --- 3. Systemd unit ---
header("3. SYSTEMD UNIT")
# The main unit file is regenerated by generate_systemd_unit() on every
# Hermes startup, so manual edits are lost. The correct approach is a
# drop-in override in hermes-gateway.service.d/override.conf.
# We check BOTH: drop-in presence + runtime ExecStart.

dropin_ok = False
if SYSTEMD_DROPIN.exists():
    dropin_content = SYSTEMD_DROPIN.read_text()
    if WRAPPER_SCRIPT.name in dropin_content:
        ok("Drop-in override uses 1Password wrapper")
        dropin_ok = True
    else:
        warn("Drop-in exists but doesn't reference wrapper script")
    if "LD_LIBRARY_PATH" in dropin_content:
        ok("Drop-in sets LD_LIBRARY_PATH")
    else:
        fail("Drop-in missing LD_LIBRARY_PATH")
else:
    # Fallback: maybe the main unit was manually edited (old approach)
    if SYSTEMD_UNIT.exists():
        unit_content = SYSTEMD_UNIT.read_text()
        if WRAPPER_SCRIPT.name in unit_content:
            warn("Wrapper in main unit file (will be lost on Hermes update -- use drop-in override)")
            dropin_ok = True
        elif "hermes_cli.main gateway run" in unit_content:
            warn("Main unit uses direct python (no wrapper) and no drop-in override")
    else:
        fail(f"Systemd unit not found: {SYSTEMD_UNIT}")

# Check runtime ExecStart (what systemd actually uses after drop-ins)
show_result = subprocess.run(
    ["systemctl", "--user", "show", "hermes-gateway", "-p", "ExecStart", "-p", "ActiveState"],
    capture_output=True, text=True,
    env={**os.environ, "XDG_RUNTIME_DIR": f"/run/user/{os.getuid()}"}
)
if show_result.stdout:
    runtime_exec = show_result.stdout
    if WRAPPER_SCRIPT.name in runtime_exec:
        ok("Runtime ExecStart uses 1Password wrapper")
    elif "hermes_cli.main gateway run" in runtime_exec and not dropin_ok:
        warn("Runtime ExecStart uses direct python (drop-in may not be loaded -- run daemon-reload)")

    if "active" in runtime_exec.lower():
        ok("Gateway is active")
    else:
        fail(f"Gateway not active: {show_result.stdout.strip()}")

# Check for invalid keys in main unit
if SYSTEMD_UNIT.exists():
    unit_content = SYSTEMD_UNIT.read_text()
    for bad_key in ["RestartMaxDelaySec", "RestartSteps"]:
        if bad_key in unit_content:
            warn(f"Invalid systemd key in main unit: {bad_key} (harmless if drop-in clears it)")

# Check LD_LIBRARY_PATH in the running process
pid_result = subprocess.run(
    ["pgrep", "-f", "hermes_cli.main gateway"],
    capture_output=True, text=True
)
if pid_result.stdout.strip():
    pid = pid_result.stdout.strip().split()[0]
    environ_result = subprocess.run(
        ["cat", f"/proc/{pid}/environ"],
        capture_output=True, text=True
    )
    if "LD_LIBRARY_PATH=/home/nuclia/.local/lib" in environ_result.stdout.replace("\0", "\n"):
        ok("Running process has LD_LIBRARY_PATH set")
    else:
        warn("LD_LIBRARY_PATH not in running process env (libopus may fail to load)")


# --- 4. Gateway logs ---
header("4. RECENT GATEWAY LOGS (voice/meeting)")
if GATEWAY_LOG.exists():
    result = subprocess.run(
        ["tail", "-200", str(GATEWAY_LOG)],
        capture_output=True, text=True
    )
    relevant = [
        l for l in result.stdout.splitlines()
        if any(k in l.lower() for k in ["voice", "meeting", "opus", "flush", "ssrc"])
    ]
    if relevant:
        ok(f"{len(relevant)} voice/meeting log lines in recent output")
        for line in relevant[-5:]:
            print(f"    {line.strip()[:120]}")
    else:
        ok("No voice/meeting activity in recent logs")
else:
    warn(f"Gateway log not found: {GATEWAY_LOG}")


# --- 5. Z.AI API key validity ---
header("5. Z.AI API KEY VALIDITY")
glm_key = None
if ENV_FILE.exists():
    for line in ENV_FILE.read_text().splitlines():
        if line.startswith("GLM_API_KEY=") and not line.startswith("#"):
            glm_key = line.split("=", 1)[1].strip().strip('"').strip("'")
            break

if glm_key:
    ok(f"GLM_API_KEY found in .env ({len(glm_key)} chars)")
    for endpoint_name, endpoint_url in [
        ("coding", "https://api.z.ai/api/coding/paas/v4/chat/completions"),
        ("regular", "https://api.z.ai/api/paas/v4/chat/completions"),
    ]:
        resp = probe_zai_endpoint(endpoint_url, glm_key).strip()
        if '"error"' in resp:
            fail(f"Z.AI {endpoint_name} endpoint: {resp[:100]}")
        elif '"choices"' in resp:
            ok(f"Z.AI {endpoint_name} endpoint: working")
        else:
            warn(f"Z.AI {endpoint_name} endpoint: unexpected response: {resp[:80]}")
else:
    fail("GLM_API_KEY not found in .env (meeting summary LLM will fail)")


# --- Summary ---
header("SUMMARY")
ok_count = sum(1 for s, _ in CHECKS if s == "OK")
warn_count = sum(1 for s, _ in CHECKS if s == "WARN")
fail_count = sum(1 for s, _ in CHECKS if s == "FAIL")
print(f"  OK: {ok_count}  WARN: {warn_count}  FAIL: {fail_count}")
print()
if fail_count > 0:
    print("  \033[31mPIPELINE NOT READY -- fix FAIL items before testing.\033[0m")
    sys.exit(1)
elif warn_count > 0:
    print("  \033[33mPIPELINE HAS WARNINGS -- review before testing.\033[0m")
    sys.exit(0)
else:
    print("  \033[32mPIPELINE READY FOR TESTING.\033[0m")
    sys.exit(0)
